version: '3'

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - product-db

  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - order-db

  product-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/product:/data/db

  order-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data/order:/data/db

